### ISSUE TITLE
How to retrieve all open orders for an account without make call for every symbol?

### ISSUE THREAD

**Issue by rakodev** [huobiapi/API_Docs_en#21]
I have to make a call for each symbol to retrieve open orders for each account?

Could we have an API endpoint like **/v1/order/matchresults** who gives all closed order but for current open orders?

**Comment by rakodev** [comment]
Of course I found the solution is to do a request on 
$endpoints = '/v1/order/orders';
With those parameters for open orders
        $options = ['states' => 'pre-submitted,submitted,partial-filled'];
And those parameters for finished orders
        $options = ['states' => 'filled'];
Without the symbol parameters.

**Comment by gelldur** [comment]
Probably open: `pre-submitted,submitting,submitted,partial-filled`

**Comment by rakodev** [comment]
there is no submitting values for this request:
**Value Range:**
pre-submitted, submitted , partial-filled , partial-canceled , filled , canceled
